upstream backend {
    server 172.18.0.2:5252;
    server 172.18.0.3:5252;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://front-end:9000;
    }

    location /api {
        proxy_pass http://backend;
    }
}
